services:
  mysql:
    image: mysql:8.0-debian
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=auth
    volumes:
      - ./authorization-server/db:/docker-entrypoint-initdb.d/
    ports:
      - 3306:3306